### ISSUE TITLE
Page Areas

### ISSUE THREAD

**Issue by tkieslich** [slub/slub_web_boersenblatt#3]
![Bildschirmfoto 2020-03-09 um 15 52 29](https://user-images.githubusercontent.com/29921835/76226953-dcbaec00-621e-11ea-8a6e-a800331ed673.png)
![Bildschirmfoto 2020-03-09 um 15 52 06](https://user-images.githubusercontent.com/29921835/76226958-ddec1900-621e-11ea-9601-acae22b9f7a2.png)

The different Pages has different Areas for content. I can use hard coded BackendLayouts for each single Page. A better and more flexible Solution would be single Gridelemnent Container for each of this Areas.
What do you think?

**Comment by albig** [comment]
I think we should have only two layouts which could be done by two (maybe one) BackendLayout:
* Search page (with results)
* Content (default) page
The video-container we won't use. So no need, to implement this.
So from my point of view a "hard coded" BackendLayout whould be sufficiant.

**Comment by tkieslich** [comment]
The above Structures come both from Content Pages (Home, Überblick) and i have no Structure for FAQ yet. So we had four BackendLayout for four Pages. If it is ok, i can Code it. 
On the other side four or five Grid Containers are nearly the same efford.
Your decision ;-)

**Comment by albig** [comment]
The FAQ should be just another content page. There will be not so much content on the whole website. So I would prefer to stay with BackendLayouts.

**Comment by tkieslich** [comment]
Ok, i have started with home BE Layout this Morning.
